### PR TITLE
Update Orleans dependancies to v1.0.10

### PR DESCRIPTION
**Pull request by andycwk**
Also updated test projects to remove dependencies on SDKs that are no longer needed as of v1.0.10 https://github.com/dotnet/orleans/releases/tag/v1.0.10

### CODE REVIEW

**Comment by richorama** [comment]
Thanks for the PR :¬)

**Comment by andycwk** [comment]
No Problem ☺

Hope I didn’t break your formatting too much – I performed a R# reformat on auto pilot and realised after sending the pull request ☹

**Comment by richorama** [comment]
Ha! I thought that was what it was.

I don't mind a bit of whitespace moving around :¬)

**Comment by richorama** [comment]
(pushed to nuget BTW)

**Comment by andycwk** [comment]
cheers  :)

**Pull request merged**
